/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fuzzymeme' at '13/05/17 21:37' with Gradle 2.14.1
 *
 * @author fuzzymeme, @date 13/05/17 21:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
